version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_service
    user: "${UID}:${GID}"  # Use environment variables to dynamically set user and group IDs
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password  # Using secrets
      POSTGRES_USER: postgres  # Custom username
      POSTGRES_DB: company148  # Initial database
    ports:
      - "5432:5432"
    volumes:
      - postgress-data:/var/lib/postgresql/data
      - ./database/initialization:/docker-entrypoint-initdb.d/
    secrets:
      - db-password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/database/postgress-volume

secrets:
  db-password:
    file: ./database/db-password  # Location of the secret file
