version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password  # Using secrets
      POSTGRES_USER: postgres  # Custom username
      POSTGRES_DB: company148  # Initial database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/initialization:/docker-entrypoint-initdb.d/
    secrets:
      - db-password

  data_analysis:
    build:
      context: ./data_analysis
    image: data_analysis_image
    container_name: data_analysis_service
    depends_on:
      - db
    environment:
      DB_PASSWORD_FILE: /run/secrets/db-password
      DB_HOST: db
    secrets:
      - db-password
    volumes:
      - shared-data:/app/data_analysis/files # Volume to share images and data with the host
      - ./data_analysis:/app/data_analysis  # Shared volume with flask-api
    restart: "no"

  flask-api:
      build:
        context: ./flask-api
      container_name: flask_api_service
      depends_on:
        - db
        - data_analysis
      volumes:
        - ./data_analysis:/app/data_analysis  # Shared volume with data_analysis
        - /var/run/docker.sock:/var/run/docker.sock # Docker socket in backend service
      ports:
        - "5000:5000"

  react-ui:
    build:
      context: ./react-ui
    container_name: react_ui_service
    depends_on:
      - flask-api
    ports:
      - "4000:3000"

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/database/postgres-volume

  shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data_analysis/files

secrets:
  db-password:
    file: ./database/db-password  # Location of the secret file