version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_service
    # user: "${UID}:${GID}"  # Use environment variables to dynamically set user and group IDs (not allowed by postgress oficial image)
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password  # Using secrets
      POSTGRES_USER: postgres  # Custom username
      POSTGRES_DB: company148  # Initial database
    ports:
      - "5432:5432"
    volumes:
      - postgress-data:/var/lib/postgresql/data
      - ./database/initialization:/docker-entrypoint-initdb.d/
    secrets:
      - db-password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  etl:
    build:
      context: ./etl
    container_name: etl_service
    depends_on:
      - db
    environment:
      DB_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - shared-data:/app/etl/files

  model:
    build:
      context: ./model
    container_name: model_service
    depends_on:
      - etl
    volumes:
      - shared-data:/app/model/files
      - model-output:/app/model/output

volumes:
  postgress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/database/postgress-volume

  shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/etl/files

  model-output:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/model/output

secrets:
  db-password:
    file: ./database/db-password  # Location of the secret file