version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password  # Using secrets
      POSTGRES_USER: postgres  # Custom username
      POSTGRES_DB: company148  # Initial database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/initialization:/docker-entrypoint-initdb.d/
    secrets:
      - db-password

  etl:
    build:
      context: ./etl
    container_name: etl_service
    depends_on:
      - db
    environment:
      DB_PASSWORD_FILE: /run/secrets/db-password
      DB_HOST: db
    secrets:
      - db-password
    volumes:
      - shared-data:/app/etl/files

  flask-api:
      build:
        context: ./flask-api
      container_name: flask_api_service
      depends_on:
        - db
        - etl
      volumes:
        - ./etl:/app/etl  # Compartir el directorio ETL para acceder al archivo YAML y el script
      ports:
        - "5000:5000"

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/database/postgres-volume

  shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/etl/files

secrets:
  db-password:
    file: ./database/db-password  # Location of the secret file