# Usa la imagen oficial de PostgreSQL como base
FROM postgres:latest

# Establecer el usuario y la base de datos
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=company148

# Expone el puerto 5432 para conexiones externas
EXPOSE 5432
