# Use the official PostgreSQL image as base
FROM postgres:latest

# Set the environment variables for the user and the database
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=company148

# Expose the port 5432 for external connections
EXPOSE 5432

# The SQL script will automatically run during the initialization of the PostgreSQL container
