connect_database: False  # Connect to Database?

excluded_columns:
  single_columns: []  # List of Index of excluded columns
  column_ranges: []  # List of range of excluded columns

# Isolation Forest
run_if: True  # Run Isolation Forest?
n_estimators: [500]  # List of values for n_estimators
max_samples: [0.9]  # List of values for max_samples
contamination: [0.05, 0.1] # Values for contamination

# DBSCAN
run_dbscan: False
eps: [0.6]
min_samples: [5]

# LOF
run_lof: False
n_neighbors: [5, 10, 20]