bootstrap:
- false
connect_database: true
contamination:
- auto
db_config:
  dbname: company148
  host: localhost
  password: '********'
  port: '5432'
  user: postgres
dbscan_save_data: false
dbscan_save_plot: false
eps:
- 1.7
excluded_columns:
  column_ranges: []
  single_columns: []
if_save_data: false
if_save_plot: false
lof_save_data: false
lof_save_plot: false
max_features:
- 1.0
max_samples:
- 0.1
min_samples:
- 2
n_estimators:
- 100
n_neighbors:
- 5
run_dbscan: true
run_if: true
run_lof: true
sql_input_data: ./files/sql/query-raw-access-data.sql
sql_output_data: ./files/sql/query-output-model-data.sql
