
sql_input_data: './files/sql/query-raw-access-data.sql'
sql_output_data: './files/sql/query-output-model-data.sql'

connect_database: False  # Connect to Database?
db_config: {
            'dbname': 'company148',
            'user': 'postgres',
            'password': 'password',
            'host': 'localhost',
            'port': '5432'
          }


excluded_columns:
  single_columns: []  # List of Index of excluded columns
  column_ranges: []  # List of range of excluded columns

# Isolation Forest
run_if: True  # Run Isolation Forest?
n_estimators: [750]  # List of values for n_estimators
max_samples: [0.9]  # List of values for max_samples
contamination: ['auto'] # Values for contamination
max_features: [0.5, 0.7, 1.0]
bootstrap: [False, True]
max_depth: [5, 10, 20]
if_save_data: False
if_save_plot: False

# DBSCAN
run_dbscan: False
eps: [1.7]
min_samples: [4]
dbscan_save_data: False
dbscan_save_plot: True

# LOF
run_lof: False
n_neighbors: [10]
lof_save_data: False
lof_save_plot: True

