sql_input_data: './files/sql/query-raw-access-data.sql'
sql_output_data: './files/sql/query-output-model-data.sql'

connect_database: True  # Connect to Database?
db_config: {
            'dbname': 'company148',
            'user': 'postgres',
            'password': '********',
            'host': 'localhost',
            'port': '5432'
          }


excluded_columns:
  single_columns: []  # List of Index of excluded columns
  column_ranges: []  # List of range of excluded columns

# Isolation Forest
run_if: True  # Run Isolation Forest?
n_estimators: [1000]  # List of values for n_estimators
max_samples: [1.0]  # List of values for max_samples
contamination: ['auto'] # Values for contamination
max_features: [0.5]
bootstrap: [False]
if_save_data: True
if_save_plot: True

# DBSCAN
run_dbscan: False
eps: [1.7]
min_samples: [4]
dbscan_save_data: True
dbscan_save_plot: True

# LOF
run_lof: False
n_neighbors: [10]
lof_save_data: True
lof_save_plot: True

