bootstrap:
- false
connect_database: true
contamination:
- 0.5
db_config:
  dbname: company148
  host: localhost
  password: '********'
  port: '5432'
  user: postgres
dbscan_save_data: true
dbscan_save_plot: true
eps:
- 1.7
excluded_columns:
  column_ranges: []
  single_columns: []
if_save_data: true
if_save_plot: true
lof_save_data: true
lof_save_plot: true
max_features:
- 0.3
max_samples:
- 0.5
min_samples:
- 4
n_estimators:
- 500
- 1000
n_neighbors:
- 20
run_dbscan: false
run_if: true
run_lof: false
sql_input_data: ./files/sql/query-raw-access-data.sql
sql_output_data: ./files/sql/query-output-model-data.sql
